version: '3.8'

services:
    orangepi_buildroot:
        container_name: orangepi_buildroot
        image: rubuschl/orangepi_buildroot
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: $USER
        user: $USER              ## docker run --user=$USER
        stdin_open: true         ## docker run -i
        tty: true                ## docker run -t
        #privileged: true

        environment:
          - USER

        volumes:
          - ~/.gitconfig:/home/$USER/.gitconfig
          - ~/.ssh:/home/$USER/.ssh
          - ./buildroot:/home/$USER/buildroot  ## folder does not need to be around
